# double xpos[] = {2.093, 3.936, 5.602, 7.834, 2.150, 3.906, 5.843, 7.567, 0.705, 4.283, 5.741, 7.483, 1.014, 2.950, 4.300, 5.806, 7.227, 1.208, 2.914, 4.405, 7.051};
# double ypos[] = {7.419, 7.199, 7.409, 7.899, 5.739, 5.781, 5.952, 5.951, 4.224, 4.015, 3.961, 3.926, 2.683, 2.549, 2.388, 2.396, 2.404, 0.978, 1.386, 1.069, 1.132};

--- name:default
# Goal heading of the robot in degrees
goal_heading: -90.0
# (X,Y) goal position of the robot
goal_position:
  data:
  - 0.705
  - 4.224

--- name:3
# Goal heading of the robot in degrees
goal_heading: -110.0
# (X,Y) goal position of the robot
goal_position:
  data:
  - 5.602
  - 7.409

--- name:4
# Goal heading of the robot in degrees
goal_heading: 90.0
# (X,Y) goal position of the robot
goal_position:
  data:
  - 7.834
  - 7.889

--- name:7
# Goal heading of the robot in degrees
goal_heading: 170.0
# (X,Y) goal position of the robot
goal_position:
  data:
  - 5.843
  - 5.952

--- name:8
# Goal heading of the robot in degrees
goal_heading: 170.0
# (X,Y) goal position of the robot
goal_position:
  data:
  - 7.567
  - 5.951

--- name:10
# Goal heading of the robot in degrees
goal_heading: 90.0
# (X,Y) goal position of the robot
goal_position:
  data:
  - 4.283
  - 4.015

--- name:13
# Goal heading of the robot in degrees
goal_heading: 65.0
# (X,Y) goal position of the robot
goal_position:
  data:
  - 1.014
  - 2.683

--- name:16
# Goal heading of the robot in degrees
goal_heading: 155.0
# (X,Y) goal position of the robot
goal_position:
  data:
  - 5.806
  - 2.396

--- name:19
# Goal heading of the robot in degrees
goal_heading: 180.0
# (X,Y) goal position of the robot
goal_position:
  data:
  - 2.914
  - 1.386

--- name:20
# Goal heading of the robot in degrees
goal_heading: 135.0
# (X,Y) goal position of the robot
goal_position:
  data:
  - 4.405
  - 1.069

--- name:21
# Goal heading of the robot in degrees
goal_heading: 135.0
# (X,Y) goal position of the robot
goal_position:
  data:
  - 7.051
  - 1.132


    
--- name:home
# Goal heading of the robot in degrees
goal_heading: 0.0
# (X,Y) goal position of the robot
goal_position:
  data:
  - 1
  - 5.5
